export const  ApiConstants = {
    URI_AUTH : "/session/signin",    
    URI_USER_CREATED : "/user/created",
    URI_USER_DESACTIVATED : "/user/desactivated",
    URI_USER_ACTIVED : "/user/activated",
    URI_USER_ACTIVES : "/user/get/actives",
    URI_ACTIVITY_CREATED: "/activity/created",
    URI_ACTIVITY_GET_ALL: "/activity/get/all",
    URI_STORE_ACTIVES : "/store/get/actives",
    URI_GET_STORE_TYPES : "/store/get/types",
    URI_GET_STORE_PRICES : "/store/get/prices",
    URI_DATE_SYSTEM: "/system/get/date",
    URI_GET_MATERIALS : "/material/get/actives",
    URI_GET_UNITS : "/material/get/units/actives",
    URI_TICKET_CREATED : "/ticket/created",
    URI_GET_TICKET_ACTIVES : "/ticket/get/actives",
    URI_GET_INVOICES_BY_TICKET : "/invoice/tickets",
    URI_CALCULATED_TICKET : "/ticket/calculated",
    URI_UPLOAD_FILE_TICKET : "/ticket/upload/file",
    URI_GENERATE_PRICE_MASSIVE : "/ticket/calculate/massive",
    URI_REPORT_TICKETS : "/ticket/generate/excel",
    URI_CREATED_PRICE : '/price/created',
    URI_MODIFIED_PRICE : '/price/modified',
    URI_VALIDATE_TICKET : '/ticket/validate',
    URI_DELETED_TICKET : '/ticket/deleted',
    URI_FAKE_USERS: "https://jsonplaceholder.typicode.com/users"
}

